### ISSUE TITLE
multi-thread demo

### ISSUE THREAD

**Issue by wunianqing** [fdwr/OnnxRuntimeDirectMLEPSample#3]
The sample project is very useful. Just with small modifications, we can make upload, run, and download parallel.

My question is, can we infer multi-data with one session in multiple threads? This is very useful when the model is small.
I already know that we can create one session for one thread. But the session itself consumes memory.

**Comment by fdwr** [comment]
I am unsure the thread safety of an ORT without looking through the docs or asking others, but I doubt this is safe. You may however be able to mitigate much of that session cost by creating distinct sessions per thread but sharing the larger tensors between them all. I forget the API function (and I'm using my phone right now), but there is one in the onnxruntime C API to do so.

**Comment by wunianqing** [comment]
Thank you very much for your response! I will look for the C API you mentioned and try it. It would be appreciated if you could post the API name here later.

**Comment by wunianqing** [comment]
I think the API is [EnableMemPattern()](https://onnxruntime.ai/docs/api/c/struct_ort_api.html#ad13b711736956bf0565fea0f8d7a5d75). But according to [this](https://onnxruntime.ai/docs/execution-providers/DirectML-ExecutionProvider.html#configuration-options), DML EP does not support it.
