### ISSUE TITLE
model.export(format="onnx", dynamic=False, simplify=True,opset=11)

### ISSUE THREAD

**Issue by mingtianquan** [fdwr/OnnxRuntimeDirectMLEPSample#4]
The exported model YOLOV8 model inference was unsuccessful. Can you provide an example

**Comment by fdwr** [comment]
Are you saying some model failed to run with this tool? What error did you see? The tool just calls ORT. So I'd contact the owners of the `export` function or open issue on ](https://github.com/microsoft/onnxruntime). You could also try [YoloV4 from here](https://github.com/onnx/models/tree/main/validated/vision/object_detection_segmentation/yolov4) to see if that works.
